/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lenovo
 */
public class fromStudentRecord extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public fromStudentRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddres = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtMath = new javax.swing.JTextField();
        txtEnglish = new javax.swing.JTextField();
        txtScience = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        txtAverage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 31, 16);

        jLabel2.setText("Addres");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 50, 20);

        jLabel3.setText("Age");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 21, 16);

        jLabel4.setText("MathGrade");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 60, 16);

        jLabel5.setText("EnglishGrade");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 60, 20);

        jLabel6.setText("ScienceGrade");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 160, 60, 20);

        jLabel7.setText("Average");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 230, 43, 16);
        getContentPane().add(txtName);
        txtName.setBounds(70, 10, 320, 20);
        getContentPane().add(txtAddres);
        txtAddres.setBounds(70, 40, 320, 20);
        getContentPane().add(txtAge);
        txtAge.setBounds(70, 70, 320, 20);
        getContentPane().add(txtMath);
        txtMath.setBounds(70, 100, 320, 22);

        txtEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnglishActionPerformed(evt);
            }
        });
        getContentPane().add(txtEnglish);
        txtEnglish.setBounds(70, 130, 320, 22);

        txtScience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScienceActionPerformed(evt);
            }
        });
        getContentPane().add(txtScience);
        txtScience.setBounds(70, 160, 320, 22);

        btnProses.setText("PROSES");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(btnProses);
        btnProses.setBounds(0, 190, 390, 30);
        getContentPane().add(txtAverage);
        txtAverage.setBounds(70, 230, 320, 30);

        setSize(new java.awt.Dimension(414, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        pbo_pratikum26.StudentRecord student = new pbo_pratikum26.StudentRecord();
         student.setName(txtName.getText());
        student.setAddres(txtAddres.getText());
        student.setAge(Integer.parseInt(txtAge.getText()));
        student.setMathGrade(Double.parseDouble(txtMath.getText()));
        student.setEnglishGrade(Double.parseDouble(txtEnglish.getText()));
        student.setScienceGrade(Double.parseDouble(txtScience.getText()));
        ////
        
        txtAverage.setText(student.getAverage()+"");
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtScienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScienceActionPerformed

    private void txtEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnglishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fromStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fromStudentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAddres;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAverage;
    private javax.swing.JTextField txtEnglish;
    private javax.swing.JTextField txtMath;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtScience;
    // End of variables declaration//GEN-END:variables
}
